agent:
  enabled: false
persistence:
  mounts:
    - mountPath: /var/run/docker.sock
      name: dockersock
      readOnly: false
    - mountPath: /usr/bin/docker
      name: docker
      readOnly: false
    - mountPath: /root/.m2
      name: maven
      readOnly: false
  volumes:
    - name: docker
      hostPath:
        path: /usr/bin/docker
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: maven
      hostPath:
        path: /root/.m2
controller:
  imagePullPolicy: "IfNotPresent"
  adminPassword: admin
  serviceType: NodePort
  nodePort: 31000
  containerSecurityContext:
    runAsUser: 0
  additionalExistingSecrets:
    - name: jenkins-secret
      keyName: dockerhub-username
    - name: jenkins-secret
      keyName: dockerhub-password
  additionalPlugins:
    - adoptopenjdk
    - job-dsl
    - maven-plugin
    - docker-plugin
    - docker-workflow
    - config-file-provider
    - pipeline-utility-steps
  JCasC:
    configScripts:
      config: |
        tool:
          mavenGlobalConfig:
            globalSettingsProvider:
              mvn:
                settingsConfigId: "global-maven-settings"
            settingsProvider: "standard"
          jdk:
            installations:
              - name: jdk16
                properties:
                  - installSource:
                      installers:
                        - adoptOpenJdkInstaller:
                            id: "jdk-16.0.2+7"
          maven:
            installations:
              - name: maven3
                properties:
                  - installSource:
                      installers:
                        - maven:
                            id: "3.8.5"        
        jobs:
          - script: >
              pipelineJob('demo') {
                  definition {
                      cpsScm {
                          scm {
                            git {
                                remote { url 'https://github.com/fvxiaoyi/gitops.git' }
                                branch '*/master'
                                extensions {}
                            }
                          }
                          scriptPath 'Jenkinsfile'
                      }
                  }
              }
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: docker-login
                      username: ${jenkins-secret-dockerhub-username}
                      password: ${jenkins-secret-dockerhub-password}
        unclassified:
          globalConfigFiles:
            configs:
              - globalMavenSettings:
                  comment: "Maven Global settings"
                  content: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
                      <mirrors>
                        <mirror>
                          <id>aliyunmaven</id>
                          <mirrorOf>central</mirrorOf>
                          <name>aliyun maven</name>
                          <url>https://maven.aliyun.com/repository/public</url>
                        </mirror>
                      </mirrors>
                    </settings>
                  id: "global-maven-settings"
                  isReplaceAll: true
                  name: "global-maven-settings"
                  providerId: "org.jenkinsci.plugins.configfiles.maven.GlobalMavenSettingsConfig"