controller:
  imagePullPolicy: "IfNotPresent"
  adminPassword: admin
  serviceType: NodePort
  nodePort: 31000
  additionalExistingSecrets:
    - name: jenkins-secret
      keyName: dockerhub-username
#    - name: jenkins-secret
#      keyName: dockerhub-password
  installPlugins:
    - configuration-as-code:1414.v878271fc496f
    - workflow-aggregator:2.6
    - adoptopenjdk:1.4
    - job-dsl:1.78.3
    - git:4.0.0
    - maven-plugin:3.18
    - docker-plugin:1.2.7
    - docker-workflow:1.28
    - config-file-provider:3.9.0
    - pipeline-utility-steps:2.12.0
    - credentials:1118.v320cd028cb_a_0
#  additionalPlugins:
#    - pipeline-utility-steps:2.12.0
  JCasC:
    configScripts:
      tool: |
        tool:
          jdk:
            installations:
              - name: jdk16
                properties:
                  - installSource:
                      installers:
                        - adoptOpenJdkInstaller:
                            id: "jdk-16.0.2+7"
          maven:
            installations:
              - name: maven3
                properties:
                  - installSource:
                      installers:
                        - maven:
                            id: "3.8.5"
      jobs: |
        jobs:
          - script: >
              pipelineJob('demo') {
                  definition {
                      cpsScm {
                          scm {
                            git {
                                remote { url 'https://github.com/fvxiaoyi/gitops.git' }
                                branch '*/master'
                                extensions {}
                            }
                          }
                          scriptPath 'Jenkinsfile'
                      }
                  }
              }
      unclassified: |
        unclassified:
          globalConfigFiles:
            configs:
              - globalMavenSettings:
                  comment: "Maven Global settings"
                  content: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
                      <mirrors>
                        <mirror>
                          <id>aliyunmaven</id>
                          <mirrorOf>central</mirrorOf>
                          <name>aliyun maven</name>
                          <url>https://maven.aliyun.com/repository/public</url>
                        </mirror>
                      </mirrors>
                    </settings>
                  id: "global-maven-settings"
                  isReplaceAll: true
                  name: "global-maven-settings"
                  providerId: "org.jenkinsci.plugins.configfiles.maven.GlobalMavenSettingsConfig"