controller:
  imagePullPolicy: "IfNotPresent"
  adminPassword: admin
  serviceType: NodePort
  nodePort: 31000
  additionalExistingSecrets:
    - name: jenkins-secret
      keyName: dockerhub-username
    - name: jenkins-secret
      keyName: dockerhub-password
  installPlugins:
    - configuration-as-code:1414.v878271fc496f
    - workflow-aggregator:2.6
    - adoptopenjdk:1.4
    - job-dsl:1.78.3
    - git:4.0.0
    - maven-plugin:3.18
    - docker-plugin:1.2.7
    - docker-workflow:1.28
    - config-file-provider:3.9.0
    - pipeline-utility-steps:2.12.0
  JCasC:
    configScripts:
      tool: |
        tool:
          jdk:
            installations:
              - name: jdk16
                properties:
                  - installSource:
                      installers:
                        - adoptOpenJdkInstaller:
                            id: "jdk-16.0.2+7"
          maven:
            installations:
              - name: maven3
                properties:
                  - installSource:
                      installers:
                        - maven:
                            id: "3.8.5"
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: docker-login
                      username: ${jenkins-secret-dockerhub-username}
                      password: ${jenkins-secret-dockerhub-password}
