controller:
  imagePullPolicy: "IfNotPresent"
  adminPassword: admin
  serviceType: NodePort
  nodePort: 31000
  installPlugins:
    - configuration-as-code:1414.v878271fc496f
    - workflow-aggregator:2.6
    - adoptopenjdk:1.4
    - job-dsl:1.78.3
    - git:4.0.0
    - maven-plugin:3.18
    - docker-plugin:1.2.7
    - docker-workflow:1.28
    - config-file-provider:3.9.0
    - pipeline-utility-steps:2.12.0
    - credentials:1118.v320cd028cb_a_0