# link https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

jenkins:
  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: docker-login
              username: ${dockerhub-username}
              password: ${dockerhub-password}

unclassified:
  globalConfigFiles:
    configs:
      - globalMavenSettings:
          comment: "Maven Global settings"
          content: |
            <?xml version="1.0" encoding="UTF-8"?>
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <mirrors>
                <mirror>
                  <id>aliyunmaven</id>
                  <mirrorOf>central</mirrorOf>
                  <name>aliyun maven</name>
                  <url>https://maven.aliyun.com/repository/public</url>
                </mirror>
              </mirrors>
            </settings>
          id: "global-maven-settings"
          isReplaceAll: true
          name: "global-maven-settings"
          providerId: "org.jenkinsci.plugins.configfiles.maven.GlobalMavenSettingsConfig"

tool:
  mavenGlobalConfig:
    globalSettingsProvider:
      mvn:
        settingsConfigId: "global-maven-settings"
    settingsProvider: "standard"
  jdk:
    installations:
      - name: jdk16
        properties:
          - installSource:
              installers:
                - adoptOpenJdkInstaller:
                    id: "jdk-16.0.2+7"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.5"