jobs:
  - script: >
      pipelineJob('demo') {
          definition {
              cpsScm {
                  scm {
                    git {
                        remote { url 'https://github.com/fvxiaoyi/gitops.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
                  scriptPath 'Jenkinsfile'
              }
          }
      }